blank_issues_enabled: true
contact_links:
  - name: EvoXD Support
    url: https://t.me/About_EvoXpro_Owner
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://aelly.tk
    about: Basic documentation for setting up.
